// ReViva — conteúdo diário. Muda à meia-noite, igual para todo mundo.
// Para acrescentar: copie uma linha, troque o texto e mantenha a vírgula no fim.
window.RV_CONTEUDO = {
  // Semente do dia: t = reflexão curta, a = micro-ação de até 2 minutos
  sementes: [
    { t: 'O luto não é um problema a resolver. É o amor procurando onde morar.', a: 'Coloque a mão no peito e respire fundo três vezes, devagar.' },
    { t: 'Hoje você não precisa ser forte. Precisa só estar aqui.', a: 'Beba um copo de água com calma, sentindo cada gole.' },
    { t: 'Saudade é a prova de que existiu algo bonito.', a: 'Escreva uma palavra que lembre essa pessoa.' },
    { t: 'Há dias de sol e dias de chuva no jardim. Os dois fazem crescer.', a: 'Abra uma janela e olhe para o céu por um minuto.' },
    { t: 'Chorar também é cuidar de si.', a: 'Se vier vontade de chorar hoje, permita. Sem pressa de parar.' },
    { t: 'Você não está esquecendo. Está aprendendo a carregar de outro jeito.', a: 'Guarde um objeto querido em um lugar especial.' },
    { t: 'Pequenos passos também são caminho.', a: 'Escolha uma única tarefa para hoje e deixe o resto para depois.' },
    { t: 'O amor não termina onde a vida termina.', a: 'Diga em voz baixa: "Eu lembro de você".' },
    { t: 'Descansar não é desistir.', a: 'Deite por cinco minutos sem celular, só respirando.' },
    { t: 'Não existe jeito certo de sentir falta de alguém.', a: 'Anote como você está agora, em uma frase.' },
    { t: 'Há uma parte de quem partiu que continua em você.', a: 'Lembre de algo que essa pessoa te ensinou.' },
    { t: 'Pedir ajuda é um ato de coragem.', a: 'Mande uma mensagem para alguém de confiança: "Pensei em você".' },
    { t: 'O corpo também sente o luto. Seja gentil com ele.', a: 'Alongue os braços para cima e solte os ombros.' },
    { t: 'Hoje pode ser um dia comum. E tudo bem.', a: 'Note uma coisa pequena e boa que aconteceu hoje.' },
    { t: 'A dor muda de tamanho. Você cresce em volta dela.', a: 'Caminhe dez minutos, mesmo que dentro de casa.' },
    { t: 'Rir não apaga o amor. Também é lembrança viva.', a: 'Lembre de um momento engraçado que vocês viveram.' },
    { t: 'As datas difíceis anunciam a chegada. Prepare um colo para você.', a: 'Marque no calendário uma data que pede cuidado.' },
    { t: 'Você está fazendo o melhor que pode com o que tem hoje.', a: 'Diga para si: "Eu estou tentando, e isso basta".' },
    { t: 'O silêncio também pode ser companhia.', a: 'Fique um minuto em silêncio, sem tela.' },
    { t: 'Cada manhã é um convite, não uma cobrança.', a: 'Arrume a cama ou um cantinho da casa.' },
    { t: 'Quem amou muito, sente muito. Isso não é fraqueza.', a: 'Escreva o nome de quem você ama em um papel.' },
    { t: 'Você pode sentir saudade e esperança no mesmo dia.', a: 'Anote algo que você espera para esta semana.' },
    { t: 'Não compare o seu luto com o de ninguém.', a: 'Respire contando até quatro ao inspirar e até seis ao soltar.' },
    { t: 'Algumas perguntas não têm resposta. Ainda assim, você segue.', a: 'Escreva uma pergunta que te acompanha.' },
    { t: 'O jardim cresce mesmo quando ninguém está olhando.', a: 'Regue uma planta ou cuide de algo vivo.' },
    { t: 'Você merece o mesmo carinho que dá aos outros.', a: 'Prepare algo gostoso para comer, só para você.' },
    { t: 'Recomeçar não significa deixar para trás.', a: 'Escolha uma música que lembre essa pessoa e escute.' },
    { t: 'Dias ruins não apagam os seus avanços.', a: 'Lembre de um dia em que você foi mais longe do que imaginava.' },
    { t: 'A saudade aperta, mas também abraça.', a: 'Abrace a si mesma por alguns segundos.' },
    { t: 'Você não precisa explicar a sua dor para ninguém.', a: 'Diga "não" para uma coisa que você não quer fazer hoje.' },
    { t: 'Cuidar da casa por dentro é tão importante quanto por fora.', a: 'Organize uma gaveta pequena.' },
    { t: 'Toda semente começa no escuro.', a: 'Antes de dormir, pense em uma intenção para amanhã.' },
    { t: 'A memória é um lugar onde ninguém vai embora.', a: 'Olhe uma foto e diga o que sente.' },
    { t: 'Não há prazo para o luto. Há o seu tempo.', a: 'Tire um tempo, mesmo curto, sem compromisso.' },
    { t: 'Você ainda pode construir dias bonitos.', a: 'Planeje uma coisa simples e boa para o fim de semana.' },
    { t: 'Falar de quem partiu é mantê-lo por perto.', a: 'Conte uma história dessa pessoa para alguém.' },
    { t: 'A culpa costuma visitar o luto. Ela não é a verdade inteira.', a: 'Escreva: "Eu fiz o que podia com o que sabia".' },
    { t: 'O sol volta, mesmo depois das noites mais longas.', a: 'Tome cinco minutos de sol, se puder.' },
    { t: 'Você é mais do que a sua perda.', a: 'Anote três coisas que fazem parte de quem você é.' },
    { t: 'Há gente que entende o que você sente. Você não está [[sozinha|sozinho|só]].', a: 'Leia um relato de outra pessoa aqui no app.' },
    { t: 'Ser gentil consigo é um jeito de honrar quem partiu.', a: 'Faça uma pausa de dois minutos entre uma tarefa e outra.' },
    { t: 'A vida pede presença, não perfeição.', a: 'Durante uma refeição, preste atenção nos sabores.' },
    { t: 'Um passo de cada vez continua sendo um passo.', a: 'Conclua uma pequena tarefa que estava parada.' },
    { t: 'Algumas raízes crescem para dentro antes de florescer.', a: 'Escreva algo que você descobriu sobre si neste tempo.' },
    { t: 'A tristeza não precisa de licença para aparecer.', a: 'Dê um nome ao que você sente agora.' },
    { t: 'Você pode guardar as lembranças e soltar o peso.', a: 'Escreva algo que você quer deixar ir e rasgue o papel.' },
    { t: 'Celebrar a vida de alguém também é luto.', a: 'Acenda uma vela ou faça um gesto simples de homenagem.' },
    { t: 'Hoje, faça só o necessário. O resto pode esperar.', a: 'Escolha o que pode ficar para amanhã, sem culpa.' },
    { t: 'O que você sente é legítimo.', a: 'Escreva uma frase começando com "Eu sinto...".' },
    { t: 'Há beleza em continuar, mesmo devagar.', a: 'Observe uma flor, uma árvore ou o céu com calma.' },
    { t: 'Quem partiu ia querer te ver em paz.', a: 'Faça algo que essa pessoa gostaria de te ver fazendo.' },
    { t: 'Você está mudando. Isso também faz parte.', a: 'Compare como você estava há um mês e como está hoje.' },
    { t: 'Ninguém floresce o tempo todo.', a: 'Permita um dia mais lento hoje.' },
    { t: 'As lágrimas regam o que ainda vai nascer.', a: 'Respire fundo e solte o ar pela boca, devagar, cinco vezes.' },
    { t: 'Gratidão e saudade podem morar juntas.', a: 'Escreva uma coisa pela qual você é grata nessa história.' },
    { t: 'O mundo pode seguir rápido. Você pode ir no seu passo.', a: 'Desacelere: faça a próxima tarefa com metade da pressa.' },
    { t: 'Você já atravessou dias que pareciam impossíveis.', a: 'Lembre de uma vez em que você se surpreendeu com a sua força.' },
    { t: 'Toda flor tem o seu tempo de abrir.', a: 'Volte a um canteiro do seu jardim que está esperando por você.' },
    { t: 'Cuidar de você hoje é plantar o amanhã.', a: 'Vá dormir um pouco mais cedo hoje.' },
    { t: 'O amor que ficou ainda pode ser dado.', a: 'Faça um gesto de carinho para alguém hoje.' }
  ],
  // Pergunta do dia (aparece no Diário)
  perguntas: [
    'O que você gostaria de contar hoje para quem partiu?',
    'Qual lembrança apareceu na sua cabeça hoje?',
    'O que tem sido mais difícil nesta semana?',
    'O que te trouxe um pouco de alívio recentemente?',
    'Que hábito dessa pessoa você reconhece em você?',
    'Se o seu dia fosse uma estação do ano, qual seria? Por quê?',
    'Quem tem estado ao seu lado neste tempo?',
    'O que você precisa ouvir hoje?',
    'Qual foi o último momento em que você sorriu?',
    'O que você sente quando pensa no futuro?',
    'Que cheiro, música ou lugar te lembra essa pessoa?',
    'O que você aprendeu sobre você desde a perda?',
    'Que conversa ficou por terminar?',
    'O que te ajuda nas noites mais difíceis?',
    'Qual pequena vitória você teve hoje?',
    'O que você gostaria de agradecer?',
    'Que parte da sua rotina mudou? Como você se sente com isso?',
    'Se pudesse pedir um conselho a essa pessoa, o que perguntaria?',
    'O que você tem evitado sentir?',
    'Que cuidado você pode oferecer a si mesma amanhã?',
    'Qual é a sua lembrança mais leve dessa pessoa?',
    'O que te deixa com medo neste momento?',
    'Onde você sente a saudade no seu corpo?',
    'O que você diria para alguém que está começando a atravessar o luto?',
    'Que data está chegando e como você quer vivê-la?',
    'O que você quer manter vivo dessa relação?',
    'O que te dá força para levantar da cama?',
    'Qual foi o momento mais bonito que vocês viveram juntos?',
    'O que você ainda não disse em voz alta?',
    'Que sonho seu ainda pode acontecer?',
    'O que te irrita ou cansa nas pessoas ao seu redor neste tempo?',
    'Que palavra descreve o seu dia?',
    'O que você faria hoje se não tivesse medo?',
    'Quem você está se tornando?',
    'Que presente essa pessoa deixou na sua vida?',
    'O que você gostaria que as pessoas entendessem sobre o seu luto?',
    'Qual lugar te traz paz?',
    'O que você perdoaria em si mesma hoje?',
    'Que ritual simples poderia te ajudar a lembrar com carinho?',
    'O que mudou no seu jeito de ver a vida?',
    'O que você quer plantar para os próximos meses?',
    'Quando você se sentiu menos [[sozinha|sozinho|só]] nesta semana?',
    'Que história dessa pessoa você quer que nunca se perca?',
    'O que você precisa soltar?',
    'O que ainda te faz sentir viva?',
    'Se você escrevesse uma carta para você daqui a um ano, o que diria?',
    'Qual conselho dessa pessoa você ainda segue?',
    'Como você tem cuidado do seu corpo?',
    'O que te emocionou recentemente?',
    'Que parte de você está florescendo, mesmo devagar?',
    'O que te ajuda a dormir melhor?',
    'Que pessoa nova ou antiga se aproximou neste tempo?',
    'O que você gostaria de fazer em homenagem a quem partiu?',
    'Qual foi a coisa mais gentil que alguém fez por você nesse período?',
    'O que você gostaria que fosse diferente amanhã?',
    'Como está a sua fé, a sua esperança ou aquilo que te sustenta?',
    'O que você sente quando ouve o nome dessa pessoa?',
    'Que parte do seu jardim pede mais cuidado agora?',
    'O que você descobriu que é capaz de fazer [[sozinha|sozinho|por conta própria]]?',
    'Se hoje fosse um capítulo da sua história, qual seria o título?'
  ]
};
