/* ReViva — trilha "Separação" (divórcio ou fim de relacionamento).
   Mesmos seis canteiros e mesmos ids de passo; aqui ficam só os textos que mudam.
   Palavras com gênero usam [[feminino|masculino|neutro]] e o app escolhe conforme a preferência da pessoa. */
window.RV_TRILHAS = {
  separacao: {
    rotulo: 'Separação',
    estacoes: {
      acolhimento: { sub: 'Chegar com calma', intro: 'O fim de uma relação também é luto, e ninguém precisa te dar permissão para sentir. A primeira estação é só para você chegar, respirar e ser [[ouvida|ouvido|escutada ou escutado]].' },
      travessia: { sub: 'O lado prático', intro: 'Divórcio, guarda, pensão, partilha e contas. Uma coisa de cada vez, e você não precisa resolver tudo hoje.' },
      elo: { sub: 'O que permanece', intro: 'Uma relação acaba, mas a história que você viveu é sua. Aqui você separa o que foi bom do que precisa ir embora.' },
      reancoragem: { sub: 'Chão debaixo dos pés', intro: 'Rotina, casa, corpo e sono mudam de lugar numa separação. Pequenas âncoras para os dias voltarem a ter contorno.' },
      ressignificacao: { sub: 'Dar sentido à história', intro: 'Não é achar culpado. É entender o que essa história deixou em você e quem você está se tornando.' },
      reviva: { sub: 'Você, de novo', intro: 'Voltar a gostar da própria companhia não é fracasso. É a vida pedindo espaço de novo.' }
    },
    missoes: {
      a1: { titulo: 'Conte sua história, do seu jeito', texto: '<p>Não existe forma certa de começar. Escreva como chegou até aqui: o que aconteceu, há quanto tempo, o que mudou na sua rotina e o que pesa mais agora.</p><p>Ninguém vai ler isso além de você.</p>', placeholder: 'Eu cheguei até aqui porque...' },
      a2: { texto: '<p>Marque o que você sente agora, sem julgamento. Numa separação é comum sentir várias coisas ao mesmo tempo, até opostas: alívio e saudade no mesmo minuto.</p>' },
      a3: { texto: '<p>Quando a dor ou a raiva apertam, o corpo entra em alerta. Respirar devagar avisa ao corpo que, neste minuto, você está [[segura|seguro|em segurança]].</p><p>Inspire acompanhando o círculo crescer e solte o ar quando ele diminuir.</p>' },
      a4: { titulo: 'O que é normal sentir numa separação', texto: '<p>Nas primeiras semanas é comum sentir <strong>raiva, alívio, culpa, vergonha, medo do futuro e saudade</strong>, às vezes tudo no mesmo dia. Também é comum sentir falta de quem você era dentro daquela relação, mesmo sabendo que ela precisava acabar.</p><p>A separação não segue fases em ordem. Vem em ondas: dias mais leves e dias em que tudo volta, principalmente perto de datas, de conversas sobre filhos ou de decisões práticas.</p><p>Uma regra que ajuda: <strong>evite decisões grandes no impulso</strong> (mudar de cidade, assinar acordos, responder mensagens difíceis de madrugada). Espere o corpo acalmar.</p><p>Procure ajuda profissional se a dor te impedir de trabalhar, comer ou dormir por muitos dias, ou se vierem pensamentos de não querer viver. CVV: <strong>188</strong>, 24 horas, gratuito.</p>' },
      t1: { titulo: 'Documentos para organizar', texto: '<p>Uma lista para você não precisar lembrar de tudo [[sozinha|sozinho|por conta própria]]. Marque o que já tem em mãos.</p>', itens: ['Certidão de casamento ou comprovante de união estável', 'RG e CPF (seus e, se tiver, da outra pessoa)', 'Certidões de nascimento dos filhos', 'Comprovantes de renda dos dois (holerites, declaração de IR)', 'Documentos de imóveis, veículos e financiamentos', 'Extratos de contas, cartões e investimentos', 'Contratos de aluguel, escola e plano de saúde', 'Comprovante de residência atual'] },
      t2: { titulo: 'Divórcio sem juridiquês', texto: '<p>No Brasil, <strong>não é preciso dar motivo</strong> para se divorciar, nem esperar prazo de separação. Basta a vontade de uma das pessoas.</p><p>Quando os dois concordam e <strong>não há filhos menores</strong> ou incapazes, o divórcio pode ser feito <strong>em cartório</strong>, com advogado, em poucos dias. Com filhos menores ou sem acordo, é na Justiça.</p><p>União estável também pode ser encerrada em cartório ou na Justiça, pelo mesmo caminho.</p><p>Quem não pode pagar advogado tem direito à <strong>Defensoria Pública</strong>, gratuita. Na dúvida, comece por lá.</p>' },
      t3: { titulo: 'Guarda e convivência, em linguagem simples', texto: '<p>Pela lei, a <strong>guarda compartilhada</strong> é a regra: os dois continuam decidindo juntos sobre escola, saúde e rotina da criança, mesmo que ela more mais tempo com um.</p><p>O que se combina é a <strong>convivência</strong>: dias da semana, fins de semana, férias, datas especiais. Quanto mais claro o combinado, menos conflito depois.</p><p>Se a conversa estiver difícil, existe <strong>mediação familiar</strong> (muitas vezes gratuita no fórum ou na Defensoria). Em situação de violência, procure a Delegacia da Mulher ou ligue <strong>180</strong>.</p>' },
      t4: { titulo: 'Retrato financeiro, sem ansiedade', texto: '<p>Um retrato simples para dar clareza sobre a sua vida financeira daqui para a frente. Marque o que já conseguiu levantar.</p>', itens: ['O que entra todo mês só na sua renda', 'Contas fixas que ficam com você (moradia, luz, escola, plano de saúde)', 'Contas conjuntas e cartões adicionais a separar', 'Dívidas e financiamentos em nome dos dois', 'Assinaturas e débitos automáticos para cancelar ou transferir'] },
      t5: { titulo: 'Pensão alimentícia, o básico', texto: '<p>A pensão para os <strong>filhos</strong> é um direito deles, não de quem cuida. O valor leva em conta a <strong>necessidade</strong> da criança e a <strong>possibilidade</strong> de quem paga; não existe percentual fixo em lei.</p><p>Pode ser combinada entre os dois e homologada, ou definida pela Justiça. Se não for paga, há caminhos legais para cobrar, inclusive desconto em folha.</p><p>Pensão entre ex-cônjuges é exceção, em geral temporária, para quem não consegue se manter no início.</p>' },
      t6: { titulo: 'Partilha de bens, sem susto', texto: '<p>O que se divide depende do <strong>regime de bens</strong>. No mais comum (comunhão parcial), divide-se o que foi <strong>adquirido durante</strong> a relação, meio a meio, e as dívidas também.</p><p>A partilha pode ser feita junto com o divórcio ou <strong>depois</strong>, com calma. Imóvel financiado, carro e FGTS usado em compra costumam entrar na conta.</p><p>Não assine nada sob pressão. Leve o documento para um advogado ou para a Defensoria antes.</p>' },
      t7: { titulo: 'Contas e vínculos para separar', texto: '<p>Não precisa ser tudo de uma vez. Marque conforme for resolvendo e peça ajuda a alguém de confiança.</p>', itens: ['Conta conjunta e cartões adicionais', 'Senhas, e-mails e nuvem compartilhados', 'Plano de saúde e dependentes', 'Beneficiários de seguros e previdência', 'Endereço de correspondência e cadastros', 'Assinaturas (streaming, aplicativos, academia)', 'Redes sociais: o que você quer manter visível'] },
      e1: { titulo: 'Escreva a carta que você não vai enviar', texto: '<p>Escreva para a pessoa de quem você está se separando. Diga o que ficou por dizer: a raiva, a mágoa, o que foi bom, o que você esperava. Não precisa ser justo nem bonito.</p><p>Essa carta não é para enviar. É para tirar de dentro. Ela fica guardada só com você.</p>', placeholder: 'Eu precisava te dizer...' },
      e2: { titulo: 'Guarde o que foi bom', texto: '<p>Mesmo no fim, houve coisas boas: um lugar, uma fase, algo que você descobriu sobre você. Guarde uma lembrança que vale a pena manter, sem o peso do resto.</p>', placeholder: 'Eu quero guardar...' },
      e3: { titulo: 'Datas que vão apertar', texto: '<p>Aniversário de casamento, datas de família, feriados com os filhos, o dia da separação. Anote as datas que você quer atravessar com mais cuidado e pense em um pequeno plano para cada uma.</p>', placeholder: 'Ex.: 20/05, aniversário de casamento. Quero jantar com amigos nesse dia.' },
      r1: { texto: '<p>Escolha três coisas pequenas e possíveis para amanhã: um copo d’água ao acordar, um banho com calma, cinco minutos de sol, uma mensagem para alguém de confiança. Âncoras para o dia ter começo.</p>' },
      r3: { texto: '<p>A separação também mora no corpo: sono, apetite e energia mudam. Marque o que você conseguiu fazer e seja gentil com o que ainda não deu.</p>' },
      r4: { titulo: 'Como falar com as crianças sobre a separação', texto: '<p>Diga com palavras simples e verdadeiras: <strong>a separação não é culpa delas</strong>, os dois continuam sendo pai e mãe, e o amor por elas não muda.</p><p>Explique o que muda (casa, dias com cada um) e o que fica (escola, amigos, rotina). Crianças aguentam bem a verdade; o que machuca é a incerteza.</p><p><strong>Não fale mal do outro</strong> perto delas, mesmo com razão. Elas são metade de cada um e sentem isso como um ataque a si mesmas.</p><p>Se ficar difícil, uma psicóloga ou um psicólogo infantil pode ajudar, e escola e pediatra também são aliados.</p>' },
      s1: { titulo: 'O que essa relação me ensinou', texto: '<p>Pense em algo que você aprendeu com essa história: sobre você, sobre o que aceita e o que não aceita mais, sobre o que quer de agora em diante. O que disso você quer levar adiante?</p>', placeholder: 'Com essa história eu aprendi...' },
      s3: { texto: '<p>Para muitas pessoas, a fé é um apoio enorme numa separação. Para outras, ela fica abalada, principalmente quando há cobrança da família ou da comunidade. As duas coisas são legítimas.</p><p>Se fizer sentido para você, reserve um momento de oração, meditação ou silêncio esta semana. Se não fizer, pule este passo sem culpa.</p>' },
      v1: { texto: '<p>Antes da relação, ou dentro dela, o que te dava prazer e ficou de lado? Escolha um passo pequeno de volta a isso e escreva quando vai dar esse passo.</p>' },
      v3: { titulo: 'Carta para quem está começando a se separar', texto: '<p>Pense em alguém que está vivendo hoje o começo que você já viveu. O que você diria? Esse é o espírito Reviva: quem já atravessou estende a mão para quem está chegando.</p>', placeholder: 'Para você, que está chegando...' }
    },
    apoio: {
      'Primeiros dias de luto': { titulo: 'Primeiros dias da separação', desc: 'Material de acolhimento para o começo, com linguagem simples e cuidadosa.' },
      'Checklist de documentos': { desc: 'Lista para organizar certidões, contratos, extratos e comprovantes.' },
      'Orientação jurídica': { desc: 'Profissionais parceiros para divórcio, guarda, pensão e partilha.' },
      'Psicólogas do luto': { titulo: 'Psicologia para recomeços', desc: 'Atendimento com profissionais que entendem de separação e luto.' }
    },
    sementes: [
      { t: 'O fim de uma relação também é luto. Você tem o direito de sentir.', a: 'Respire fundo três vezes, devagar, com a mão no peito.' },
      { t: 'Alívio e saudade podem morar no mesmo dia.', a: 'Anote, em uma frase, como você está agora.' },
      { t: 'Você não falhou. Uma história terminou.', a: 'Diga em voz baixa: "Eu fiz o que pude com o que sabia".' },
      { t: 'Raiva é energia procurando saída. Dê a ela um lugar seguro.', a: 'Escreva o que te dá raiva e feche o caderno.' },
      { t: 'Sua casa pode ter novo cheiro, nova luz, novo jeito.', a: 'Mude um objeto de lugar ou abra uma janela diferente.' },
      { t: 'Não responda mensagens difíceis à noite. Amanhã você ainda será você.', a: 'Deixe o celular fora do quarto hoje.' },
      { t: 'Quem você era antes ainda existe. Está só debaixo de poeira.', a: 'Lembre de algo que você gostava e parou de fazer.' },
      { t: 'Cuidar de si não é egoísmo. É base.', a: 'Prepare uma refeição com calma, só para você.' },
      { t: 'As crianças precisam de pais em paz, não de pais perfeitos.', a: 'Se tiver filhos, diga a eles uma coisa boa hoje.' },
      { t: 'Datas apertam. Avisar a si [[mesma|mesmo|mesma ou mesmo]] já é cuidado.', a: 'Marque a próxima data difícil e pense em um plano pequeno.' },
      { t: 'Você não precisa explicar a sua separação para ninguém.', a: 'Pratique uma resposta curta e gentil para perguntas invasivas.' },
      { t: 'Solidão e estar só não são a mesma coisa.', a: 'Faça uma coisa que você gosta sem companhia, com atenção.' },
      { t: 'Rir de novo não é trair a sua dor.', a: 'Assista a algo que te faça rir por dez minutos.' },
      { t: 'O corpo também está se separando. Seja gentil com ele.', a: 'Alongue os ombros e o pescoço por um minuto.' },
      { t: 'Dividir contas é prático. Dividir culpa não ajuda ninguém.', a: 'Escolha uma pendência prática e dê um passo nela hoje.' },
      { t: 'Você pode guardar o que foi bom e soltar o resto.', a: 'Escreva algo que você quer soltar e rasgue o papel.' },
      { t: 'Amizades que ficaram paradas estão esperando um oi.', a: 'Mande uma mensagem para alguém que você sente falta.' },
      { t: 'Decisões grandes podem esperar o coração desacelerar.', a: 'Adie uma decisão que não é urgente.' },
      { t: 'A pessoa que vai cuidar de você nos próximos meses é você. Confie nela.', a: 'Anote três coisas que você faz bem.' },
      { t: 'Chorar no banho conta. Chorar no carro conta. Chorar conta.', a: 'Se vier vontade de chorar hoje, permita.' },
      { t: 'Não compare a sua travessia com a de ninguém.', a: 'Saia das redes sociais por algumas horas hoje.' },
      { t: 'Um lar se faz de novo com pequenas repetições.', a: 'Crie um ritual pequeno para a noite: um chá, uma música, uma leitura.' },
      { t: 'Ser [[ouvida|ouvido|escutada ou escutado]] muda o tamanho da dor.', a: 'Conte para alguém de confiança como foi o seu dia.' },
      { t: 'A sua história não acabou. Ela mudou de capítulo.', a: 'Escreva um título para a fase que está começando.' },
      { t: 'Pedir ajuda jurídica cedo evita dor depois.', a: 'Anote uma dúvida prática para levar a quem entende.' },
      { t: 'O silêncio da casa também pode virar descanso.', a: 'Fique um minuto em silêncio, sem tela.' },
      { t: 'Você está mais perto do fim do começo do que imagina.', a: 'Compare como você estava há um mês e como está hoje.' },
      { t: 'Dizer não é uma frase completa.', a: 'Diga não para uma coisa que você não quer fazer hoje.' },
      { t: 'A culpa gosta de visitar quem se importa. Ela não é a verdade inteira.', a: 'Escreva uma coisa que você fez certo nessa história.' },
      { t: 'Recomeçar não é voltar ao início. É seguir com o que você aprendeu.', a: 'Planeje uma coisa simples e boa para o fim de semana.' }
    ],
    perguntas: [
      'O que você gostaria de dizer e não disse?',
      'O que mudou na sua rotina que mais pesa hoje?',
      'O que te trouxe um pouco de alívio nesta semana?',
      'Quem tem estado ao seu lado neste tempo?',
      'O que você precisa ouvir hoje?',
      'Qual foi o último momento em que você sorriu?',
      'O que você sente quando pensa no futuro?',
      'O que você descobriu sobre você desde a separação?',
      'Que parte de você ficou guardada dentro da relação e quer voltar?',
      'O que te ajuda nas noites mais difíceis?',
      'Qual pequena vitória você teve hoje?',
      'O que você quer manter dessa história? E o que quer deixar ir?',
      'Que data está chegando e como você quer vivê-la?',
      'O que te dá medo neste momento?',
      'Onde você sente a raiva ou a tristeza no seu corpo?',
      'O que você diria para alguém que está começando a se separar agora?',
      'O que você aceita e o que não aceita mais em uma relação?',
      'Qual lugar te traz paz?',
      'O que você perdoaria em si [[mesma|mesmo|mesma ou mesmo]] hoje?',
      'Como você tem cuidado do seu corpo?',
      'Se tiver filhos: o que eles precisam ouvir de você esta semana?',
      'Quando você se sentiu menos [[sozinha|sozinho|só]] nesta semana?',
      'O que você gostaria que as pessoas entendessem sobre a sua separação?',
      'Que conselho você daria a quem você era há um ano?',
      'O que ainda te faz sentir [[viva|vivo|com vida]]?',
      'Que ritual simples poderia marcar este novo começo?',
      'Qual é o seu maior alívio nesta fase, mesmo que dê culpa admitir?',
      'O que você quer plantar para os próximos meses?',
      'Que pessoa nova ou antiga se aproximou neste tempo?',
      'Se hoje fosse um capítulo da sua história, qual seria o título?'
    ]
  }
};
